dx = input('Enter the x from the encoding program: ')
dy = input('Enter the y from the encoding program: ')
dx = list(dx.split('.'))
dy = list(dy.split('.'))
dx[0] = int(dx[0])
dy[0] = int(dy[0])
dx[0] = int(round((dx[0]+7)**(1/2)))
dy[0] = int(round((dy[0]+6)**(1/3)))
dx[-1] = list(dx[-1])
dx[-1].insert(1, '.')
dx[-1] = ''.join(dx[-1])
dx[-1] = int(round(float(dx[-1])))
dy[-1] = list(dy[-1])
dy[-1].insert(1, '.')
dy[-1] = ''.join(dy[-1])
dy[-1] = int(round(float(dy[-1])))
print('The result of origin X is: '+str(dx[0])+'.'+str(dx[-1]))
print('The result of origin Y is: '+str(dy[0])+'.'+str(dy[-1]))
