dx = float(input('Enter original x in float format: '))
dy = float(input('Enter original y in float format: '))
dxi = int(dx)
dyi = int(dy)
dxj = str(dx-dxi)
dyj = str(dy-dyi)
enx = str(dxi**2-7)
eny = str(dyi**3-6)
print('Encrypted x is: '+' '+enx+'.'+dxj)
print('Encrypted y is: '+' '+eny+'.'+dyj)
